In [1]:
import numpy as np

In [2]:
a = np.array((0, 1, 2, 3))
print(a)
print(type(a))

[0 1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [5]:
print (a.shape)

(4,)


In [6]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)

[[1 2 3]
 [4 5 6]]


numpy.arange

In [11]:
a = np.arange(10,15,.5)
type(a)
a

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [12]:
a = np.array([0, 1, 2, 3])

In [13]:
# Why it is useful: Memory efficient container that provides fast numerical operations.

In [14]:
import time 

In [15]:
time.time()

1652354904.384134

In [18]:
#python lists
start = time.time()
L = range(10000000)
x = [i**2 for i in L]
end = time.time()
print("time taken is",end-start,"seconds")


time taken is 4.543866157531738 seconds


In [19]:
start = time.time()
a = np.arange(10000000)
a**2
end = time.time()
print("time taken is",end-start,"seconds")

time taken is 0.033185720443725586 seconds


# 1. Creating arrays
1.1 Manual Constrution of arrays

In [20]:
# 1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [21]:
# print dimensions
a.ndim

1

In [22]:
#shape
a.shape

(4,)

In [23]:
len(b)

2

In [24]:
# 2-D

b = np.array([[0, 1],
             [3,4]
             ])
b

array([[0, 1],
       [3, 4]])

In [25]:
b.ndim

2

In [26]:
type(b.shape)


tuple

In [27]:
len(b) #return the size of the first dimension

2

In [28]:
# 3D and so on
c = np.array([
    [
        [0,1],
        [2,3]
    ],
    [
        [4,5],
        [6,7]
    ]
])
print(c)
print(c.ndim)
print(c.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)


# 1.2 Functions for creating arrays


In [29]:
# using arange function
# arange is an array- valued version of the built in python range function

a= np.arange(10) # 0.....n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = np.arange(1,10) # start,end (exclusive), step
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#using linspace
a = np.linspace(0, 0.9, 10) # start, end, number of points
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [36]:
#common arrays: numpy.ones
a = np.ones((3, 3, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [37]:
# np.Zeros
b = np.zeros((4,3))
b


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#np. eye
c = np.eye(4, 3, k=0)    #Return a 2-D array with ones on the diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [39]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [40]:
#np.diag
#Create array using diag function

a = np.diag([1, 2, 3, 4,], k=2) # construct diagonal array
print(a)
print(a.shape)

[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(6, 6)


In [41]:
#np.diag to extract diagonal
np.diag(a)

array([0, 0, 0, 0, 0, 0])

In [42]:
#create array using random

#create an array of the given shape and populate it with random sapmles from a uniform
a = np.random.rand(3,2)

a

array([[0.07298342, 0.12576255],
       [0.30915806, 0.91996422],
       [0.18873352, 0.52933627]])

In [43]:
print(dir(np.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uni

In [44]:
a = np.random.randn(4, 3) # Return a sample (or sample)

a

array([[ 0.69204174, -1.07047291,  0.4891111 ],
       [-0.80452374, -1.68880179, -0.52221596],
       [-0.18598819, -0.68321086, -0.92725886],
       [-0.275859  ,  0.61929098,  1.63736836]])

# 2. Basic Data Types

In [46]:
a= np.arange(10)

a.dtype

dtype('int32')

In [47]:
# you can explicitly specify which data-type you want:

a = np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
a = np.arange(10,dtype="int32")
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#the default data is flaot for zeros and ones function
a = np.zeros((3,3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

Other datatypes

In [52]:
d= np.array([1+2j, 2+4j])     #complex datatype

print(d.dtype)

complex128


In [53]:
b = np.array([True, False, True, False])  # Boolean Datatype

print(b.dtype)

bool


In [55]:
# unicode
s = np.array(["Ram","Robert","Rahinijjm"])
s.dtype

dtype('<U9')

In [56]:
# 3. Indexing and Slicing 
3.1 Indexing 
The items of an array can be accessed 